### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by bonabasri** [luqmaha/simaya#1]
Selamat Siang mas, bolehkah saya minta database aplikasi simayanya
kalau boleh minta tolong dikirimkan ke email saya di bonabasri@gmail.com.
terima kasih

**Comment by luqmaha** [comment]
terima kasih atas partisipasinya
silahkan cek email untuk databasenya

**Comment by ragasubekti** [comment]
Saya juga minta database aplikasi simaya, tolong dikirim ke rfilmriot@gmail.com. Terimakasih

**Comment by luqmaha** [comment]
sudah tak kirim ke email @ragasubekti

**Comment by sipiyuku** [comment]
request databasenya ke email = sipiyuku@gmail.com   makasih

**Comment by luqmaha** [comment]
sudah tak kirim @sipiyuku

**Comment by Aankprast** [comment]
Mohon databasenya mas. Terima kasih aankprast@gmail.com

**Comment by luqmaha** [comment]
done @Aankprast

**Comment by Aankprast** [comment]
Terima Kasih Mas. Oh ya. untuk passwornya apa mas

**Comment by luqmaha** [comment]
cek email untuk password @Aankprast

**Comment by yogiigabe** [comment]
mohon databasenya kak. terima kasih

yogiigabe@gmail.com

**Comment by luqmaha** [comment]
done @yogiigabe

**Comment by zoelfikarrsia** [comment]
Selamat Siang mas, bolehkah saya minta aplikasi simaya dan database beserta passwdnya, jika berkenan mohon dikirim ke email: zoelfikarrsia@gmail.com, terima kasih

**Comment by budi58** [comment]
Selamat Siang mas, bolehkah saya minta aplikasi simaya dan database beserta passwdnya, jika berkenan mohon dikirim ke email: Budi.tri58@gmail.com, terima kasih

**Comment by lordzeday** [comment]
Mohon bantuannya untuk database dikirim ke email zeday.ro@gmail.com

Terima kasih

**Comment by fachrur898** [comment]
bisa minta databasenya mas, dikirim ke email: fachrur898@gmail.com

Terima kasih

**Comment by bennyadr** [comment]
Selamat Sore Mas Luqman, mohon ijin jika berkenan untuk share database simaya, email saya benny.adrianto@gmail.com terima kasih banyak sebelumnya...semoga sukses terus dengan tugas dan karirnya..salam
